<?php require_once 'config.php';
$user_logged_in = (isset($_SESSION['loggedin']) && $_SESSION['loggedin'] === true && isset($_SESSION['id']));
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Courses | EduPro</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
         tailwind.config = { theme: { extend: { colors: { 'purple-600': '#7c3aed', 'purple-700': '#6d28d9', 'purple-800': '#5b21b6', 'purple-50': '#f5f3ff', 'purple-100': '#ede9fe', 'purple-500': '#8b5cf6', 'blue-500': '#3b82f6', 'green-500': '#22c55e', 'yellow-500': '#eab308', primary: { 600: '#7c3aed', 700: '#6d28d9', }, secondary: { 400: '#60a5fa', 500: '#3b82f6' } }, fontFamily: { sans: ['Inter', 'sans-serif'], } } } }
    </script>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');
        body { font-family: 'Inter', sans-serif; }
        .course-card { transition: all 0.3s ease; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05); }
        .course-card:hover { transform: translateY(-5px); box-shadow: 0 10px 15px rgba(0, 0, 0, 0.1); }
        .filter-chip { transition: all 0.2s ease; }
        .filter-chip.active { background-color: #7c3aed; color: white; }
        .tooltip { opacity: 0; transition: opacity 0.2s ease; pointer-events: none; position: absolute; z-index: 10; }
        .has-tooltip:hover .tooltip { opacity: 1; }
    </style>
</head>
<body class="bg-gray-50 text-gray-900">
    <nav class="bg-white shadow-sm">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"> <div class="flex justify-between h-16 items-center"> <div class="flex items-center"> <a href="Home.php" class="flex items-center"> <i class="fas fa-graduation-cap text-purple-600 text-2xl mr-2"></i> <span class="text-xl font-bold">EduPro</span> </a> <div class="hidden md:block ml-10"> <div class="flex space-x-4"> <a href="courses_list.php" class="px-3 py-2 rounded-md text-sm font-medium text-purple-600 bg-purple-50">Courses</a> <a href="#" class="px-3 py-2 rounded-md text-sm font-medium text-gray-500 hover:text-gray-900">Recommendations</a> <a href="#" class="px-3 py-2 rounded-md text-sm font-medium text-gray-500 hover:text-gray-900">Learning Paths</a> <a href="#" class="px-3 py-2 rounded-md text-sm font-medium text-gray-500 hover:text-gray-900">For Business</a> </div> </div> </div> <div class="hidden md:block"> <div class="flex items-center"> <div class="relative mx-4"> <input type="text" placeholder="Search courses..." class="bg-gray-100 text-gray-800 px-4 py-2 rounded-md w-64 focus:outline-none focus:ring-2 focus:ring-purple-500"> <button class="absolute right-3 top-2.5 text-gray-500"> <i class="fas fa-search"></i> </button> </div> <button class="p-2 rounded-full hover:bg-gray-100 relative has-tooltip"> <i class="fas fa-bell text-gray-500"></i> <span class="tooltip -bottom-8 left-1/2 transform -translate-x-1/2 bg-gray-800 text-white text-xs py-1 px-2 rounded whitespace-nowrap"> Notifications </span> </button> <div class="ml-3 relative"> <?php if($user_logged_in): ?> <a href="Dashboard.php" title="Profile/Dashboard"> <img class="h-8 w-8 rounded-full" src="<?php echo $_SESSION['profile_image_url'] ?? 'https://randomuser.me/api/portraits/lego/1.jpg'; ?>" alt="Profile"> </a> <?php else: ?> <a href="Login.php" class="px-4 py-2 rounded-md text-sm font-medium hover:bg-gray-100 transition">Log in</a> <a href="Signup.php" class="ml-2 px-4 py-2 bg-purple-600 text-white rounded-md text-sm font-medium hover:bg-purple-700 transition">Sign up</a> <?php endif; ?> </div> </div> </div> <div class="md:hidden"> <button class="mobile-menu-button p-2 rounded-md hover:bg-gray-100 focus:outline-none"> <i class="fas fa-bars"></i> </button> </div> </div> </div>
    </nav>

    <main class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div class="flex flex-col md:flex-row justify-between items-start md:items-end mb-8"> <div> <h1 class="text-2xl md:text-3xl font-bold mb-2">All Courses</h1> <p class="text-gray-600">Explore our comprehensive library of courses.</p> </div> </div>
        <div class="mb-8"> <h2 class="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-3">Filter by</h2> <div class="flex flex-wrap gap-3"> <button class="filter-chip active px-4 py-2 rounded-full bg-purple-100 text-purple-800 text-sm font-medium"> All Courses </button> <button class="filter-chip px-4 py-2 rounded-full bg-gray-100 text-gray-800 hover:bg-gray-200 text-sm font-medium"> <i class="fas fa-laptop-code text-purple-500 mr-2"></i> Tech Skills </button> <button class="filter-chip px-4 py-2 rounded-full bg-gray-100 text-gray-800 hover:bg-gray-200 text-sm font-medium"> <i class="fas fa-chart-line text-blue-500 mr-2"></i> Business </button> <button class="filter-chip px-4 py-2 rounded-full bg-gray-100 text-gray-800 hover:bg-gray-200 text-sm font-medium"> <i class="fas fa-paint-brush text-green-500 mr-2"></i> Creative </button> <button class="filter-chip px-4 py-2 rounded-full bg-gray-100 text-gray-800 hover:bg-gray-200 text-sm font-medium"> <i class="fas fa-bolt text-yellow-500 mr-2"></i> Quick Skills </button> </div> </div>

        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-12">
             <div class="course-card bg-white rounded-xl overflow-hidden border border-gray-200 flex flex-col"> <div class="relative"><a href="ai_course.php"><img src="https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80" alt="AI Course" class="w-full h-48 object-cover"></a><div class="absolute top-3 left-3 bg-white text-purple-600 px-2 py-1 rounded-md text-xs font-bold">BESTSELLER</div></div> <div class="p-5 flex flex-col flex-grow"><div class="flex items-center mb-2"><div class="flex items-center text-yellow-400 text-sm"><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star-half-alt"></i></div><span class="ml-1 text-sm text-gray-500">(12,450)</span></div><a href="ai_course.php"><h3 class="font-bold text-lg mb-2 hover:text-purple-700 flex-grow">Artificial Intelligence Fundamentals</h3></a><p class="text-gray-600 text-sm mb-4">Master the core concepts...</p><div class="flex items-center justify-between mt-auto"><div class="flex items-center"><i class="fas fa-user-graduate text-gray-400 mr-2 text-sm"></i><span class="text-sm text-gray-500">8,500+ students</span></div></div><div class="mt-4 pt-4 border-t border-gray-100"><div class="flex justify-between"><a href="ai_course.php" class="flex-1 mr-2"><button class="w-full bg-purple-600 hover:bg-purple-700 text-white py-2 px-4 rounded-md text-sm font-medium transition">View Details</button></a></div></div></div> </div>
             <div class="course-card bg-white rounded-xl overflow-hidden border border-gray-200 flex flex-col"> <div class="relative"><a href="js_course.php"><img src="https://images.unsplash.com/photo-1626785774573-4b799315345d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80" alt="JavaScript Course" class="w-full h-48 object-cover"></a></div> <div class="p-5 flex flex-col flex-grow"><div class="flex items-center mb-2"><div class="flex items-center text-yellow-400 text-sm"><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i></div><span class="ml-1 text-sm text-gray-500">(8,720)</span></div><a href="js_course.php"><h3 class="font-bold text-lg mb-2 hover:text-purple-700 flex-grow">Modern JavaScript Mastery</h3></a><p class="text-gray-600 text-sm mb-4">From ES6+ to advanced patterns...</p><div class="flex items-center justify-between mt-auto"><div class="flex items-center"><i class="fas fa-user-graduate text-gray-400 mr-2 text-sm"></i><span class="text-sm text-gray-500">15,300+ students</span></div></div><div class="mt-4 pt-4 border-t border-gray-100"><div class="flex justify-between"><a href="js_course.php" class="flex-1 mr-2"><button class="w-full bg-purple-600 hover:bg-purple-700 text-white py-2 px-4 rounded-md text-sm font-medium transition">View Details</button></a></div></div></div> </div>
             <div class="course-card bg-white rounded-xl overflow-hidden border border-gray-200 flex flex-col"> <div class="relative"><a href="ds_py_course.php"><img src="https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80" alt="Data Science Course" class="w-full h-48 object-cover"></a><div class="absolute top-3 left-3 bg-white text-purple-600 px-2 py-1 rounded-md text-xs font-bold">NEW</div></div> <div class="p-5 flex flex-col flex-grow"><div class="flex items-center mb-2"><div class="flex items-center text-yellow-400 text-sm"><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star-half-alt"></i></div><span class="ml-1 text-sm text-gray-500">(5,320)</span></div><a href="ds_py_course.php"><h3 class="font-bold text-lg mb-2 hover:text-purple-700 flex-grow">Data Science with Python</h3></a><p class="text-gray-600 text-sm mb-4">Complete guide to data analysis...</p><div class="flex items-center justify-between mt-auto"><div class="flex items-center"><i class="fas fa-user-graduate text-gray-400 mr-2 text-sm"></i><span class="text-sm text-gray-500">6,800+ students</span></div></div><div class="mt-4 pt-4 border-t border-gray-100"><div class="flex justify-between"><a href="ds_py_course.php" class="flex-1 mr-2"><button class="w-full bg-purple-600 hover:bg-purple-700 text-white py-2 px-4 rounded-md text-sm font-medium transition">View Details</button></a></div></div></div> </div>
             <div class="course-card bg-white rounded-xl overflow-hidden border border-gray-200 flex flex-col"> <div class="relative"><a href="react_course.php"><img src="https://images.unsplash.com/photo-1633356122544-f134324a6cee?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80" alt="React Course" class="w-full h-48 object-cover"></a><div class="absolute top-3 left-3 bg-white text-purple-600 px-2 py-1 rounded-md text-xs font-bold">HOT</div></div> <div class="p-5 flex flex-col flex-grow"><div class="flex items-center mb-2"><div class="flex items-center text-yellow-400 text-sm"><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i></div><span class="ml-1 text-sm text-gray-500">(10,240)</span></div><a href="react_course.php"><h3 class="font-bold text-lg mb-2 hover:text-purple-700 flex-grow">React.js Complete Guide</h3></a><p class="text-gray-600 text-sm mb-4">Build modern web applications...</p><div class="flex items-center justify-between mt-auto"><div class="flex items-center"><i class="fas fa-user-graduate text-gray-400 mr-2 text-sm"></i><span class="text-sm text-gray-500">22,100+ students</span></div></div><div class="mt-4 pt-4 border-t border-gray-100"><div class="flex justify-between"><a href="react_course.php" class="flex-1 mr-2"><button class="w-full bg-purple-600 hover:bg-purple-700 text-white py-2 px-4 rounded-md text-sm font-medium transition">View Details</button></a></div></div></div> </div>
             <div class="course-card bg-white rounded-xl overflow-hidden border border-gray-200 flex flex-col"> <div class="relative"><a href="uiux_course.php"><img src="https://images.unsplash.com/photo-1541462608143-67571c6738dd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80" alt="UX Design Course" class="w-full h-48 object-cover"></a></div> <div class="p-5 flex flex-col flex-grow"><div class="flex items-center mb-2"><div class="flex items-center text-yellow-400 text-sm"><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star-half-alt"></i></div><span class="ml-1 text-sm text-gray-500">(3,870)</span></div><a href="uiux_course.php"><h3 class="font-bold text-lg mb-2 hover:text-purple-700 flex-grow">UX/UI Design Fundamentals</h3></a><p class="text-gray-600 text-sm mb-4">Learn user-centered design...</p><div class="flex items-center justify-between mt-auto"><div class="flex items-center"><i class="fas fa-user-graduate text-gray-400 mr-2 text-sm"></i><span class="text-sm text-gray-500">5,200+ students</span></div></div><div class="mt-4 pt-4 border-t border-gray-100"><div class="flex justify-between"><a href="uiux_course.php" class="flex-1 mr-2"><button class="w-full bg-purple-600 hover:bg-purple-700 text-white py-2 px-4 rounded-md text-sm font-medium transition">View Details</button></a></div></div></div> </div>
             <div class="course-card bg-white rounded-xl overflow-hidden border border-gray-200 flex flex-col"> <div class="relative"><a href="aws_course.php"><img src="https://images.unsplash.com/photo-1550751827-4bd374c3f58b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80" alt="Cloud Computing Course" class="w-full h-48 object-cover"></a><div class="absolute top-3 left-3 bg-white text-purple-600 px-2 py-1 rounded-md text-xs font-bold">POPULAR</div></div> <div class="p-5 flex flex-col flex-grow"><div class="flex items-center mb-2"><div class="flex items-center text-yellow-400 text-sm"><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i></div><span class="ml-1 text-sm text-gray-500">(4,560)</span></div><a href="aws_course.php"><h3 class="font-bold text-lg mb-2 hover:text-purple-700 flex-grow">Cloud Computing with AWS</h3></a><p class="text-gray-600 text-sm mb-4">Master AWS services...</p><div class="flex items-center justify-between mt-auto"><div class="flex items-center"><i class="fas fa-user-graduate text-gray-400 mr-2 text-sm"></i><span class="text-sm text-gray-500">7,300+ students</span></div></div><div class="mt-4 pt-4 border-t border-gray-100"><div class="flex justify-between"><a href="aws_course.php" class="flex-1 mr-2"><button class="w-full bg-purple-600 hover:bg-purple-700 text-white py-2 px-4 rounded-md text-sm font-medium transition">View Details</button></a></div></div></div> </div>
             <div class="course-card bg-white rounded-xl overflow-hidden border border-gray-200 flex flex-col"> <div class="relative"><a href="dm_course.php"><img src="https://images.unsplash.com/photo-1499750310107-5fef28a66643?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80" alt="Digital Marketing Course" class="w-full h-48 object-cover"></a></div> <div class="p-5 flex flex-col flex-grow"><div class="flex items-center mb-2"><div class="flex items-center text-yellow-400 text-sm"><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star-half-alt"></i></div><span class="ml-1 text-sm text-gray-500">(6,780)</span></div><a href="dm_course.php"><h3 class="font-bold text-lg mb-2 hover:text-purple-700 flex-grow">Digital Marketing Masterclass</h3></a><p class="text-gray-600 text-sm mb-4">SEO, Social Media, PPC...</p><div class="flex items-center justify-between mt-auto"><div class="flex items-center"><i class="fas fa-user-graduate text-gray-400 mr-2 text-sm"></i><span class="text-sm text-gray-500">9,100+ students</span></div></div><div class="mt-4 pt-4 border-t border-gray-100"><div class="flex justify-between"><a href="dm_course.php" class="flex-1 mr-2"><button class="w-full bg-purple-600 hover:bg-purple-700 text-white py-2 px-4 rounded-md text-sm font-medium transition">View Details</button></a></div></div></div> </div>
             <div class="course-card bg-white rounded-xl overflow-hidden border border-gray-200 flex flex-col"> <div class="relative"><a href="ios_course.php"><img src="https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80" alt="iOS Development Course" class="w-full h-48 object-cover"></a><div class="absolute top-3 left-3 bg-white text-purple-600 px-2 py-1 rounded-md text-xs font-bold">NEW</div></div> <div class="p-5 flex flex-col flex-grow"><div class="flex items-center mb-2"><div class="flex items-center text-yellow-400 text-sm"><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i></div><span class="ml-1 text-sm text-gray-500">(2,340)</span></div><a href="ios_course.php"><h3 class="font-bold text-lg mb-2 hover:text-purple-700 flex-grow">iOS Development with SwiftUI</h3></a><p class="text-gray-600 text-sm mb-4">Build beautiful iOS apps...</p><div class="flex items-center justify-between mt-auto"><div class="flex items-center"><i class="fas fa-user-graduate text-gray-400 mr-2 text-sm"></i><span class="text-sm text-gray-500">3,800+ students</span></div></div><div class="mt-4 pt-4 border-t border-gray-100"><div class="flex justify-between"><a href="ios_course.php" class="flex-1 mr-2"><button class="w-full bg-purple-600 hover:bg-purple-700 text-white py-2 px-4 rounded-md text-sm font-medium transition">View Details</button></a></div></div></div> </div>
             <div class="course-card bg-white rounded-xl overflow-hidden border border-gray-200 flex flex-col"> <div class="relative"><a href="cybersec_course.php"><img src="https://images.unsplash.com/photo-1550751827-4bd374c3f58b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80" alt="Cybersecurity Course" class="w-full h-48 object-cover"></a><div class="absolute top-3 left-3 bg-white text-purple-600 px-2 py-1 rounded-md text-xs font-bold">TRENDING</div></div> <div class="p-5 flex flex-col flex-grow"><div class="flex items-center mb-2"><div class="flex items-center text-yellow-400 text-sm"><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star-half-alt"></i></div><span class="ml-1 text-sm text-gray-500">(3,120)</span></div><a href="cybersec_course.php"><h3 class="font-bold text-lg mb-2 hover:text-purple-700 flex-grow">Cybersecurity Essentials</h3></a><p class="text-gray-600 text-sm mb-4">Protect systems and networks...</p><div class="flex items-center justify-between mt-auto"><div class="flex items-center"><i class="fas fa-user-graduate text-gray-400 mr-2 text-sm"></i><span class="text-sm text-gray-500">4,500+ students</span></div></div><div class="mt-4 pt-4 border-t border-gray-100"><div class="flex justify-between"><a href="cybersec_course.php" class="flex-1 mr-2"><button class="w-full bg-purple-600 hover:bg-purple-700 text-white py-2 px-4 rounded-md text-sm font-medium transition">View Details</button></a></div></div></div> </div>
             <div class="course-card bg-white rounded-xl shadow-md overflow-hidden border border-gray-200 flex flex-col"> <div class="relative"><a href="web_dev_course.php"><img src="https://images.unsplash.com/photo-1555066931-4365d14bab8c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80" alt="Web Development" class="w-full h-48 object-cover"></a><div class="absolute top-2 right-2 bg-yellow-500 text-white text-xs font-bold px-2 py-1 rounded">Bestseller</div></div> <div class="p-6 flex flex-col flex-grow"><div class="flex items-center"><span class="inline-block px-2 py-1 text-xs font-semibold bg-purple-100 text-purple-800 rounded">Beginner</span><span class="ml-2 text-xs text-gray-500"><i class="fas fa-clock"></i> 45 hours</span></div><a href="web_dev_course.php"><h3 class="mt-3 text-xl font-semibold text-gray-900 hover:text-purple-700 flex-grow">Complete Web Development Bootcamp</h3></a><p class="mt-2 text-gray-600 text-sm mb-4">Master HTML, CSS, JavaScript...</p><div class="mt-4 flex items-center"><div class="flex items-center text-yellow-400"><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star-half-alt"></i></div><span class="ml-2 text-sm text-gray-600">4.7 (12,345)</span></div><div class="mt-4 pt-4 border-t border-gray-100 flex justify-between items-center"><span class="text-lg font-bold text-gray-900">₹499</span><a href="web_dev_course.php" class="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition text-sm">View Details</a></div></div> </div>
             <div class="course-card bg-white rounded-xl shadow-md overflow-hidden border border-gray-200 flex flex-col"> <div class="relative"><a href="ai_ml_course.php"><img src="" alt="AI & ML Course" class="w-full h-48 object-cover bg-gray-300"></a></div> <div class="p-5 flex flex-col flex-grow"><a href="ai_ml_course.php"><h3 class="font-bold text-lg mb-2 hover:text-purple-700 flex-grow">AI & Machine Learning Bootcamp</h3></a><p class="text-gray-600 text-sm mb-4">Description...</p><div class="mt-auto pt-4 border-t border-gray-100"><a href="ai_ml_course.php" class="flex-1 mr-2"><button class="w-full bg-purple-600 hover:bg-purple-700 text-white py-2 px-4 rounded-md text-sm font-medium transition">View Details</button></a></div></div> </div>
             <div class="course-card bg-white rounded-xl shadow-md overflow-hidden border border-gray-200 flex flex-col"> <div class="relative"><a href="business_mgmt_course.php"><img src="" alt="Business Course" class="w-full h-48 object-cover bg-gray-300"></a></div> <div class="p-5 flex flex-col flex-grow"><a href="business_mgmt_course.php"><h3 class="font-bold text-lg mb-2 hover:text-purple-700 flex-grow">Business Management & Leadership</h3></a><p class="text-gray-600 text-sm mb-4">Description...</p><div class="mt-auto pt-4 border-t border-gray-100"><a href="business_mgmt_course.php" class="flex-1 mr-2"><button class="w-full bg-purple-600 hover:bg-purple-700 text-white py-2 px-4 rounded-md text-sm font-medium transition">View Details</button></a></div></div> </div>
             <div class="course-card bg-white rounded-xl shadow-md overflow-hidden border border-gray-200 flex flex-col"> <div class="relative"><a href="data_science_course.php"><img src="" alt="Data Science Course" class="w-full h-48 object-cover bg-gray-300"></a></div> <div class="p-5 flex flex-col flex-grow"><a href="data_science_course.php"><h3 class="font-bold text-lg mb-2 hover:text-purple-700 flex-grow">The Complete Data Science Course</h3></a><p class="text-gray-600 text-sm mb-4">Description...</p><div class="mt-auto pt-4 border-t border-gray-100"><a href="data_science_course.php" class="flex-1 mr-2"><button class="w-full bg-purple-600 hover:bg-purple-700 text-white py-2 px-4 rounded-md text-sm font-medium transition">View Details</button></a></div></div> </div>
        </div>
    </main>

    <footer class="bg-white border-t border-gray-200"> <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12"></div> </footer>

    <script>
         document.addEventListener('DOMContentLoaded', function() { document.querySelectorAll('.filter-chip').forEach(chip => {}); document.querySelectorAll('.bookmark-btn').forEach(btn => {}); const mobileMenuButton = document.querySelector('.mobile-menu-button'); if (mobileMenuButton) { mobileMenuButton.addEventListener('click', function() {}); } const searchInput = document.querySelector('input[type="text"]'); const searchButton = searchInput ? searchInput.nextElementSibling : null; if (searchButton) { searchButton.addEventListener('click', function() {}); } if (searchInput) { searchInput.addEventListener('keypress', function(e) {}); } });
     </script>
</body>
</html>